apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver    
  replicas: 1
  template:
    metadata:
      labels:
        app: "goserver"
    spec:
      containers:
        - name: goserver
          image: "osdeving/teste-go:v7.1"
          ports:
          - containerPort: 80

          envFrom:
            - configMapRef:
                name: goserver-env

            - secretRef:
                name: goserver-secret
                
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: goserver-env
data:
  spring.boot.application: "golang não é spring boot app"
  NAME: "Willams Santos de Sousa"
  AGE: "39"
---
apiVersion: v1
kind: Secret
metadata:
  name: goserver-secret
data:
  USERNAME: "d2lsbGFtcwo="
  PASSWORD: "MTIzNDU2Cg=="
---
apiVersion: v1
kind: Service
metadata:
  name: goserver-svc
spec:
  selector:
    app: goserver
  type: ClusterIP
  ports:
  - name: goserver-svc
    port: 80
    targetPort: 80
    protocol: TCP
        