apiVersion: apps/v1
kind: Deployment
metadata:
  name: javabootapi
  labels:
    app: javabootapi
spec:
  selector:
    matchLabels:
      app: javabootapi    
  replicas: 1
  template:
    metadata:
      labels:
        app: "javabootapi"
    spec:
      containers:
        - name: javabootapi
          image: "osdeving/demo-spring-boot-docker:v2"
          ports:
          - containerPort: 2225

          envFrom:
            - configMapRef:
                name: javabootapi-env

            - secretRef:
                name: javabootapi-secret
                
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: javabootapi-env
data:
  spring.boot.application: "golang não é spring boot app"
  NAME: "Willams Santos de Sousa"
  AGE: "39"
---
apiVersion: v1
kind: Secret
metadata:
  name: javabootapi-secret
data:
  USERNAME: "d2lsbGFtcwo="
  PASSWORD: "MTIzNDU2Cg=="
---
apiVersion: v1
kind: Service
metadata:
  name: javabootapi-svc
spec:
  selector:
    app: javabootapi
  type: NodePort
  ports:
  - name: javabootapi-svc
    port: 2225
    nodePort: 30000
    protocol: TCP
        