spring:
    output:
        ansi:
            enabled: ALWAYS
server:
    port: 2225

management:
    endpoints:
        enabled-by-default: true
        jmx:
            exposure:
                include: "*"
        web:
            exposure:
                include: "*"
    endpoint:
        info:
            enabled: true
